ViewModels/HomeViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Laptop> avaLaptops { get; set; }
    }
}

ViewModels/LaptopsListViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class LaptopsListViewModel
    {

        public IEnumerable<Laptop> allLaptops { get; set; }

        public string currentCategory { get; set; }
    }
}

ViewModels/ShopCartViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAllLaptops _laptopRep;

        public HomeController(IAllLaptops lapRep)
        {
            _laptopRep = lapRep;
        }

        public ViewResult Index()
        {
            var homeLaptops = new HomeViewModel
            {
                avaLaptops = _laptopRep.getAvailableLaptops
            };
            return View(homeLaptops);
        }

    }
}

Controllers/LaptopsController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class LaptopsController : Controller
    {
        private readonly IAllLaptops _allLaptops;

        private readonly ILaptopCategory _allCategories;


        public LaptopsController(IAllLaptops iAllLaptops, ILaptopCategory iLaptopCategory)
        {
            _allLaptops = iAllLaptops;
            _allCategories = iLaptopCategory;
        }


        [Route("Laptops/List")]
        [Route("Laptops/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Laptop> laptops = null;
            string currCategory = "";
            if(string.IsNullOrEmpty(category))
            {
                laptops = _allLaptops.Laptops.OrderBy(i => i.id);
            }
            else
            {
                if(string.Equals("work", category, StringComparison.OrdinalIgnoreCase))
                {
                    laptops = _allLaptops.Laptops.Where(i => i.Category.categoryName.Equals("Для работы")).OrderBy(i => i.id);
                    currCategory = "For work";
                }
                else if (string.Equals("gaming", category, StringComparison.OrdinalIgnoreCase))
                {
                    laptops = _allLaptops.Laptops.Where(i => i.Category.categoryName.Equals("Для игр")).OrderBy(i => i.id);
                    currCategory = "For games";
                }
                currCategory = _category;
            }

            var lapObj = new LaptopsListViewModel
            {
                allLaptops = laptops,
                currentCategory = currCategory
            };

            return View(lapObj);
        }

    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class OrderController : Controller
    {

        private readonly IAllOrders allOrders;

        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }


        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopCart.listShopItems = shopCart.getShopItems();

            if(shopCart.listShopItems.Count == 0)
            {
                ModelState.AddModelError("","You have to have at least one laptop in your cart");
            }

            if(ModelState.IsValid)
            {
                allOrders.createOrder(order);
                return RedirectToAction("Complete");
            }

            return View(order);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Order has been saved!";
            return View();
        }

    }
}

Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllLaptops _laptopRep;

        private readonly ShopCart _shopCart;

        public ShopCartController(IAllLaptops lapRep, ShopCart shopCart)
        {
            _laptopRep = lapRep;
            _shopCart = shopCart;
        }

        public ViewResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.listShopItems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };
            return View(obj);
        }

        public RedirectToActionResult addToCart(int id)
        {
            var item = _laptopRep.Laptops.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }

    }
}

Views/Home/Index.cshtml
@model HomeViewModel

<h1>Available laptops</h1>
<div class="row mt-5 mb-2">
    @{
        foreach (Shop.Data.Models.Laptop laptop in Model.avaLaptops)
        {
            @Html.Partial("AllLaptops", laptop)
        }
    }
</div>

Views/Laptops/List.cshtml
<h1>Laptops</h1>
<div class="row mt-5 mb-2">
    @{ 
        foreach(Shop.Data.Models.Laptop laptop in Model.allLaptops)
        {
            @Html.Partial("AllLaptops", laptop)
        }
    }
</div>

Views/Order/Checkout.cshtml
@model Shop.Data.Models.Order

<div class="row">
    <div class="container"><h3>Order Details</h3></div>
    <form asp-action="Checkout" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="name"></label>
            <div class="col-md-5">
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="surName"></label>
            <div class="col-md-5">
                <input asp-for="surName" class="form-control" />
                <span asp-validation-for="surName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="phone"></label>
            <div class="col-md-5">
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="email"></label>
            <div class="col-md-5">
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="address"></label>
            <div class="col-md-5">
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Make an order" />
    </form>
</div>

Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

Views/Shared/AllLaptops.cshtml
@model Shop.Data.Models.Laptop

    <div class="col-lg-3">
        <img class="img-thumbnail" src="@Model.img" alt="@Model.name" />
        <h2>@Model.name</h2>
        <p>@Model.price</p>
        <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.id">Add to Cart</a></p>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet"type="text/css" />
</head>
<body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <a class="navbar-brand" href="/Home/">WorldOfLaptops</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/ShopCart/">Cart<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Laptops/List/gaming">Gaming Laptops<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Laptops/List/work">For Work Laptops<span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                    <form class="form-inline mt-2 mt-md-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </nav>
        </header>

    <div class="container mt-5">
        @RenderBody()
    </div>

    <hr class="featurette-divider container">

    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>© 2020 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
    </footer>

    <script href="~/js/bootstrap.min.js"></script>
</body>
</html>

Views/ShopCart/Index.cshtml
@model ShopCartViewModel
    <div class="container">
        @foreach (var el in Model.shopCart.listShopItems)
        {
            <div class="alert alert-warning mt-3">
                <b>Laptop:</b>@el.laptop.name<br/>
                <b>Price</b>@el.laptop.price.ToString()
            </div>
        }
        <hr />
        <a class="btn btn-danger mb-5" asp-controller="Order" asp-action="Checkout">Buy</a>

    </div>